=== soylent/jschema/test/support/fixtures/json_schema1.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "items": {
        "properties": {
            "dimensions": {
                "properties": {
                    "height": {
                        "type": "number"
                    },
                    "length": {
                        "type": "number"
                    },
                    "width": {
                        "type": "number"
                    }
                },
                "required": [
                    "length",
                    "width",
                    "height"
                ],
                "type": "object"
            },
            "id": {
                "description": "The unique identifier for a product",
                "type": "number"
            },
            "name": {
                "type": "string"
            },
            "price": {
                "exclusiveMinimum": true,
                "minimum": 0,
                "type": "number"
            },
            "tags": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array",
                "uniqueItems": true
            },
            "warehouseLocation": {
                "$ref": "http://json-schema.org/geo",
                "description": "Coordinates of the warehouse with the product"
            }
        },
        "required": [
            "id",
            "name",
            "price"
        ],
        "title": "Product",
        "type": "object"
    },
    "title": "Product set",
    "type": "array"
}

=== soylent/jschema/test/support/fixtures/json_data1.json
[
    {
        "dimensions": {
            "height": 9.5,
            "length": 7.0,
            "width": 12.0
        },
        "id": 2,
        "name": "An ice sculpture",
        "price": 12.5,
        "tags": [
            "cold",
            "ice"
        ],
        "warehouseLocation": {
            "latitude": -78.75,
            "longitude": 20.4
        }
    },
    {
        "dimensions": {
            "height": 1.0,
            "length": 3.1,
            "width": 1.0
        },
        "id": 3,
        "name": "A blue mouse",
        "price": 25.5,
        "warehouseLocation": {
            "latitude": 54.4,
            "longitude": -32.7
        }
    }
]
